# Generated by Django 3.1.5 on 2021-01-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.TextField(max_length=255)),
                ('descripcion', models.TextField()),
                ('estatus', models.SmallIntegerField(default=1)),
            ],
        ),
    ]
