# Generated by Django 3.1.5 on 2021-01-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0002_auto_20210119_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.CharField(max_length=50)),
                ('orden', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
